apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: hecate-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      serviceAccountName: monitoring-agent
      containers:
        - name: policy-service
          image: hecate/policy-service:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"