apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch-hecate
    url: http://elasticsearch:9200
    access: proxy
    isDefault: false
    editable: false
    database: "application_logs-*"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
      includeFrozen: false
